CREATE TABLE IF NOT EXISTS Authors (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    author VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS Books (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    book VARCHAR(255) NOT NULL,
    author_id INT UNSIGNED NOT NULL,
    INDEX books_author_id (author_id),
    CONSTRAINT books_author_fk FOREIGN KEY (author_id) REFERENCES Authors(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
